erDiagram
    USER {
        uuid id
        string first_name
        string last_name
        string email
        string password
        bool is_admin
    }
    BUSINESS {
        uuid id
        string name
        string description
        string email
        int phone_number
        uuid user_id
    }
    LOCATION {
        uuid id
        string name
        string description
        int capacity
        uuid user_id
        uuid business_id
    }
    RESERVATION {
        uuid id
        string client_name
        string reason
        date date
        int slot
        string status
        uuid user_id
        uuid location_id
    }

    USER ||--o{ BUSINESS: owns
    USER ||--o{ LOCATION: owns
    BUSINESS ||--o{ LOCATION: has
    LOCATION ||--o{ RESERVATION: has

